### ISSUE TITLE
博客网站无法访问

### ISSUE THREAD

**Issue by shaolyy** [WrRan/blog.io-archived-2020#1]
访问博客网站，无法打开页面，提示：由于存在网络安全性问题，该站点已停止访问。

**Comment by WrRan** [comment]
谢谢您的关注。目前在申请“域名备案”，所以导致此问题；等到域名成功备案，网站就可以成功访问啦~

**Comment by WrRan** [comment]
@shaolyy 
你好，我暂且将博客迁移到 http://47.110.235.226/
请惠存 :)
